/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.balam.data.structures.and.algorithms;

public class App {
    public static void main(String[] args) {
        System.out.println("Hello, World!");
    }

    public int add(int a, int b) {
        return a + b;
    }
}
